Update Sing Up, Sign In, Sign Out feature
dinosysOrg/sportbook-ios pull request #2
Opened 2017-05-25 10:47 UTC by ducbm051291

- Authentication Storyboard, ViewControllers and ViewModelfor Sign In, Sign Up and Forgotpassword
- Authentication, Tournament, Skill API for API Request
- Some Helpers and extensions
- Models for parse data
- UserManager for store authentication data
[Update]
- Podfile with some new lib pod
- MainStoryboard with Logout Button for test logout function

2017-05-30 05:04 UTC, ndduy requested changes

2017-05-30 05:04 UTC, ndduy commented on SportBook/Application/AppDelegate.swift
> +            let mainVc = UIStoryboard.loadMainViewController()
Let's agree to not use Vc but use ViewController

2017-05-30 05:04 UTC, ndduy commented on SportBook/Managers/AuthManager.swift
> +            return "Dữ liệu phản hồi lỗi!!!"
Please integrate with Localization directly instead of hard coding text

2017-05-30 05:04 UTC, ndduy commented on SportBook/Application/AppDelegate.swift
> +        }
What will happen if it is not authenticated

2017-05-30 05:04 UTC, ndduy commented on SportBook/Helpers/Extension/UIStoryboard+Loader.swift
> +        return loadFromAuth("LoginViewController") as! MainViewController
as LoginViewController?

2017-05-30 05:04 UTC, ndduy commented on SportBook/Services/SkillAPI.swift
> +public enum Skill  {
Can we change to SkillAPI to differentiate with the Skill Object

2017-05-30 05:04 UTC, ndduy commented on SportBook/Services/TournamentAPI.swift
> +public enum Tournament  {
Same as Skill

2017-05-30 05:04 UTC, ndduy commented on SportBook/ViewModels/LoginViewModel.swift
> +    let emailValid: Driver<Bool>
Driver?

2017-05-30 05:04 UTC, ndduy commented on SportBook/Views/AuthenticationView/LoginViewController.swift
> +    @IBOutlet weak var btnLogin: UIButton!
I thought we are going to use RxView?

2017-05-30 05:04 UTC, ndduy commented on SportBook/Views/AuthenticationView/LoginViewController.swift
> +        tfEmail.tintColor = overcastBlueColor
can we move this into ios uiappearance

2017-05-30 05:04 UTC, ndduy commented on SportBook/Views/AuthenticationView/SignupViewController.swift
> +    let overcastBlueColor = UIColor(red: 0, green: 187/255, blue: 204/255, alpha: 1.0)
ios uiappearance

2017-05-30 06:19 UTC, ducbm051291 commented on SportBook/Views/AuthenticationView/SignupViewController.swift
> +    let overcastBlueColor = UIColor(red: 0, green: 187/255, blue: 204/255, alpha: 1.0)
Ok

2017-05-30 06:19 UTC, ducbm051291 commented on SportBook/Views/AuthenticationView/LoginViewController.swift
> +        tfEmail.tintColor = overcastBlueColor
Ok

2017-05-30 06:19 UTC, ducbm051291 commented on SportBook/Views/AuthenticationView/LoginViewController.swift
> +    @IBOutlet weak var btnLogin: UIButton!
Yes. We're using RxCocoa

2017-05-30 06:19 UTC, ducbm051291 commented on SportBook/ViewModels/LoginViewModel.swift
> +    let emailValid: Driver<Bool>
It's belong to RxCocoa for binding data to UI

2017-05-30 06:20 UTC, ducbm051291 commented on SportBook/Services/SkillAPI.swift
> +public enum Skill  {
Agree

2017-05-30 06:20 UTC, ducbm051291 commented on SportBook/Services/TournamentAPI.swift
> +public enum Tournament  {
Ok

2017-05-30 06:20 UTC, ducbm051291 commented on SportBook/Managers/AuthManager.swift
> +            return "Dữ liệu phản hồi lỗi!!!"
Yes, Gonna do it

2017-05-30 06:20 UTC, ducbm051291 commented on SportBook/Application/AppDelegate.swift
> +        }
App will launch Login Storyboard as default

2017-05-30 06:20 UTC, ducbm051291 commented on SportBook/Application/AppDelegate.swift
> +            let mainVc = UIStoryboard.loadMainViewController()
Yes. Agree

2017-05-30 06:20 UTC, ducbm051291 commented on SportBook/Helpers/Extension/UIStoryboard+Loader.swift
> +        return loadFromAuth("LoginViewController") as! MainViewController
Yes. My bad!

2017-05-31 07:23 UTC, ndduy approved these changes

2017-05-31 07:23 UTC, merged