Separate project into Staging and Production
dinosysOrg/sportbook-ios pull request #4
Opened 2017-06-07 10:01 UTC by ducbm051291

Add RxReachability and ReachabilitySwift for handle detecting network changed
Add CachedManager for cached data in case of no internet connection
Update Facebook AppID for Staging and Production

2017-06-09 05:19 UTC, ndduy requested changes

2017-06-09 05:19 UTC, ndduy commented on SportBook/Managers/CachedManager.swift
> +}
Cached file de lam gi?

2017-06-09 05:19 UTC, ndduy commented on SportBook/Views/MainView/TournamentViewController.swift
>  }
please separate the tableview delegate to different extension

2017-06-09 06:01 UTC, ducbm051291 commented on SportBook/Managers/CachedManager.swift
> +}
E tính dùng để cached dữ liệu lưu lại vô file *.plist để lỡ lần sau chạy ứng dụng ko load đc từ server thì load cached lên để hiển thị :)

2017-06-09 06:01 UTC, ducbm051291 commented on SportBook/Views/MainView/TournamentViewController.swift
>  }
ok a

2017-06-19 03:31 UTC, ndduy approved these changes

2017-06-19 03:31 UTC, merged